# ! JUST READ - don't change the content of this file
# Server settings with final resolved parameters
# (includes sd_server() parameters, YAML header, and defaults)
use_cookies: yes
auto_scroll: no
rate_survey: no
all_questions_required: yes
start_page: welcome
system_language: en
highlight_unanswered: yes
highlight_color: gray
capture_metadata: yes
required_questions:
- next_veh_when
- next_veh_market
- next_veh_style
- attention_check_toyota
- household_veh_count
- household_veh_fuel
- charger_access
- neighbor_ev_info
- primary_veh_fuel
- primary_veh_new_used
- primary_veh_obtain_how
- primary_veh_cost
- primary_veh_payment
- primary_veh_mpg
- primary_veh_refuel
- primary_veh_range
- next_veh_budget
- next_veh_payment
- next_veh_fuel_new_phev
- next_veh_fuel_used_phev
- next_veh_fuel_new_bev
- next_veh_fuel_used_bev
- next_veh_nobev
- next_veh_car_images
- next_veh_suv_images
- vehicle_cbc_q0_button
- vehicle_cbc_q1_button
- vehicle_cbc_q2_button
- vehicle_cbc_q3_button
- vehicle_cbc_q4_button
- vehicle_cbc_q5_button
- vehicle_cbc_q6_button
- battery_cbc_q1_button
- battery_cbc_q2_button
- battery_cbc_q3_button
- battery_cbc_q4_button
- battery_cbc_q5_button
- battery_cbc_q6_button
- no_bev_selected0
- battery_attribute_veh_mile
- battery_attribute_purchase_price
- battery_attribute_battery_refurbish
- battery_attribute_battery_health
- run_on_gasoline
- plugged_in
- know_electric_vehicle
- write_electric_name
- max_subsidy
- attitudes_1_a_ev_norm
- attitudes_1_a_ev_cost
- attitudes_1_a_ev_environment
- attitudes_1_b_ev_range
- attitudes_1_b_ev_resale
- attitudes_1_b_ev_price
- attitudes_2_a_ev_battery_environment
- attitudes_2_a_ev_battery_function
- attitudes_2_a_attention_check_agree
- attitudes_2_b_price_sensitive
- attitudes_2_b_tech_savvy
- attitudes_2_b_risk_taker
- birth_year
- gender
- ethnicity
- race
- hh_size
- employment
- hh_income
- education
- housing_type
- housing_tenure
- electric_bill
- political_view
- party_voting
- climate_change
- home_zipcode
- attention_check_survey_content

