# ! JUST READ - don't change the content of this file
# All survey configuration settings with final resolved values

theme-settings:
  theme: default
  barposition: top
  barcolor: ~
  footer-left: ''
  footer-center: ''
  footer-right: ''

survey-settings:
  show-previous: no
  use-cookies: yes
  auto-scroll: no
  rate-survey: no
  all-required: no
  start-page: ~
  system-language: en
  highlight-unanswered: yes
  highlight-color: gray
  capture-metadata: yes
  required: ~
  shuffled: ~
  all-shuffled: no

system-messages:
  cancel: Cancel
  confirm-exit: Confirm Exit
  sure-exit: Are you sure you want to exit the survey?
  submit-exit: Submit and Exit
  warning: Warning
  required: Please answer all required questions before proceeding.
  rating-title: Before you go...
  rating-text: 'Rate your survey experience:'
  rating-scale: from 1-poor to 5-excellent
  previous: Previous
  next: Next
  exit: Exit Survey
  restart: Restart Survey
  close-tab: Please close this tab manually to exit the survey.
  choose-option: Choose an option...
  click: Click here
  redirect: Redirecting in
  seconds: seconds
  new-tab: Opens in a new tab
  redirect-error: "Error: This text won't trigger any redirection..."
